User can see the social media on end
Ailurotech/wp-landing pull request #28
Opened 2024-06-09 20:17 UTC by sguming

[acf-export-2024-06-09.json](https://github.com/user-attachments/files/15754093/acf-export-2024-06-09.json)
<img width="1277" alt="image" src="https://github.com/Ailurotech/wp-landing/assets/84424033/3a526c5b-408f-4faa-a2f0-9d4b658f2992">
a 1050x150 div contan 4 x150x150 icon

2024-06-09 22:46 UTC, RuntaoZhuge requested changes

2024-06-09 22:46 UTC, RuntaoZhuge commented on html/wp-content/themes/ailurotech/src/scss/style.scss
> +@import 'socialmedia';
follow the naming convention please

2024-06-09 22:46 UTC, RuntaoZhuge commented on html/wp-content/themes/ailurotech/views/base.twig
> +    <link rel="stylesheet" href="{{ theme.link }}/dist/css/socialmedia.css">
No need to import individual ones

2024-06-09 22:46 UTC, RuntaoZhuge commented on html/wp-content/themes/ailurotech/views/base.twig
> +{% include 'partial/socialmedia.twig' %}
You don't want this social media always show up in main

2024-06-09 22:46 UTC, RuntaoZhuge commented on html/wp-content/themes/ailurotech/views/partial/footer.twig
> +    <p>nihao</p>
Remove this hard coded thing

2024-06-09 22:46 UTC, RuntaoZhuge commented on html/wp-content/themes/ailurotech/views/partial/index.twig
> -    <h1>Hello</h1>
Again, remove these hardcoded or debug code

2024-06-09 22:46 UTC, RuntaoZhuge commented on html/wp-content/themes/ailurotech/views/partial/socialmedia.twig
> +
This is too hardcoded, these icons can be any icons I put on WordPress. Make it dynamic rather than hardcode everything

2024-06-10 20:14 UTC, sguming commented
这行代码不起作用诶，我style.css 里面定义的class也就是图标的大小排列没办法用诶<link rel="stylesheet" href="{{ theme.link }}/dist/css/style.css">
[acf-export-2024-06-10.json](https://github.com/user-attachments/files/15778614/acf-export-2024-06-10.json)
然后其他的我应该弄完了 麻烦您检查一下，我把debug和hardcode的代码删了，然后用explode分开空格，这样可以随便改图标

2024-06-10 20:29 UTC, sguming commented
我暂时把它放在base.twig里面了 如果解决了问题之后我会改掉，但是css莫名不工作，不知道怎么办

2024-06-11 04:58 UTC, RuntaoZhuge commented
Resolve conflicts please

2024-06-11 11:44 UTC, merged