21 users can find related links at the bottom of the site
Ailurotech/wp-landing pull request #31
Opened 2024-06-12 12:03 UTC by sguming

<img width="1435" alt="image" src="https://github.com/Ailurotech/wp-landing/assets/84424033/53e9db51-a392-4a26-8da7-485a67142edf">
[acf-export-2024-06-12.json](https://github.com/user-attachments/files/15804347/acf-export-2024-06-12.json)
这边title 使用空格 分辨几个title，link使用！换行#换列， 使用js来加入动作，代码在mainjs里面，具体function会等基本做完之后挨个实现，

2024-06-12 20:42 UTC, sguming commented
之后也会做成function加入footer，但是由于上一个branch没弄好，function没法render所以暂时搁置在这去做下一个了

2024-06-13 01:35 UTC, RuntaoZhuge requested changes
There are some changes to be made and don't just straight copy and paste what chatgpt dump there, you need to read the code before you submit a pull request

2024-06-13 01:35 UTC, RuntaoZhuge commented on html/wp-content/themes/ailurotech/LInk.php
The Name is wrong

2024-06-13 01:35 UTC, RuntaoZhuge commented on html/wp-content/themes/ailurotech/LInk.php
> +$title="Company Products Support";
What are these hardcoded values for?

2024-06-13 01:35 UTC, RuntaoZhuge commented on html/wp-content/themes/ailurotech/src/scss/_link.scss
This is an empty file

2024-06-13 01:35 UTC, RuntaoZhuge commented on html/wp-content/themes/ailurotech/views/base.twig
> +    {% include 'partial/link.twig' %}
Don't need to remove footer

2024-06-13 01:35 UTC, RuntaoZhuge commented on html/wp-content/themes/ailurotech/views/partial/link.twig
This name is too generic, needs more detailed naming

2024-06-13 01:35 UTC, RuntaoZhuge commented on html/wp-content/themes/ailurotech/views/partial/link.twig
> +        /* 标题的样式 */
What is this empty css

2024-06-13 01:35 UTC, RuntaoZhuge commented on html/wp-content/themes/ailurotech/views/partial/link.twig
> +</style>
We don't use inline css or css in twig. This is most likely to fail

2024-06-13 01:35 UTC, RuntaoZhuge commented on html/wp-content/themes/ailurotech/views/partial/link.twig
> +            <h2 class="title">{{ titles[loop.index0] }}</h2> <!-- 为标题设置 class="title" -->
This class is very generic

2024-06-13 01:35 UTC, RuntaoZhuge commented on html/wp-content/themes/ailurotech/views/partial/link.twig
> +                <span class="link">{{ item }}</span><br> <!-- 为链接设置 class="link" -->
This class is very generic

2024-06-13 11:39 UTC, closed without merging