22 feature section
Ailurotech/wp-landing pull request #38
Opened 2024-07-06 13:38 UTC by sguming

<img width="1249" alt="image" src="https://github.com/Ailurotech/wp-landing/assets/84424033/cd03973d-c9c4-4bb8-8469-b47c003c5e1a">
[acf-export-2024-07-06.json](https://github.com/user-attachments/files/16116233/acf-export-2024-07-06.json)
11am-5pm thursday Friday and Saturday
19 hours

2024-07-06 13:57 UTC, sguming commented
Conflict solve

2024-07-10 06:33 UTC, RuntaoZhuge requested changes
@codeWorld666 Can you have a functional testing on this ticket?

2024-07-10 06:33 UTC, RuntaoZhuge commented on html/wp-content/themes/ailurotech/src/scss/feature-section.scss
> +        font-size: 75%; /* 字体大小为 3vw 或者 20px 中的较小值 */
Remove chatgpt comments please

2024-07-10 06:33 UTC, RuntaoZhuge commented on html/wp-content/themes/ailurotech/index.php
> +$context['feature_icon'] = explode(" ", $feature_icon);
Can you make these consistent? This is very confusing when sometimes sepreated by space, !, and ,

2024-07-10 06:33 UTC, RuntaoZhuge commented on html/wp-content/themes/ailurotech/index.php
> +$context['feature_right_details_number']=explode(" ",$feature_right_details_number);
Then you can make this more concise by just passing in a string and having the out put as a list

2024-07-10 06:33 UTC, RuntaoZhuge commented on html/wp-content/themes/ailurotech/src/scss/_footer.scss
> +    margin-top: 80px;
This looks kind of hard coded need more testing

2024-07-10 06:33 UTC, RuntaoZhuge commented on html/wp-content/themes/ailurotech/views/partial/feature-section.twig
> +      </div>
What would happen if I only have 1 item in the loop?[loop.index-1] would it be pointing to -1 index?

2024-07-10 06:33 UTC, RuntaoZhuge commented on html/wp-content/themes/ailurotech/views/base.twig
> +      {% include 'partial/feature-section.twig' %}
Move this into content don't place directly in base

2024-07-15 05:09 UTC, codeWorld666 commented
1. Please remove the debug notice at the top of the page.
2. please remove the extra percentage symbols
3. no blue progress bar
<img width="468" alt="image" src="https://github.com/user-attachments/assets/b6e8c44f-19d8-4699-8a5c-2468b8a1712e">

<img width="412" alt="image" src="https://github.com/user-attachments/assets/14b09183-dd00-4f31-8314-f61d9e4c29cd">

<img width="336" alt="image" src="https://github.com/user-attachments/assets/df7a68dc-8a43-4c37-9f62-1fee328857a0">
@RuntaoZhuge @sguming

2024-07-15 05:14 UTC, codeWorld666 commented on html/wp-content/themes/ailurotech/views/partial/index.twig
> +        {% include 'partial/feature-section.twig' %}
Please move the feature section above the contact section.

2024-07-15 06:46 UTC, sguming commented
[acf-export-2024-07-15.json](https://github.com/user-attachments/files/16230847/acf-export-2024-07-15.json)

2024-07-15 21:35 UTC, sguming commented
1,  all of acf get_field in this component i change to use "!", and please modify them, or just use wp-all-import plugin to import 
[Pages-Export-2024-July-15-2117.csv](https://github.com/user-attachments/files/16240518/Pages-Export-2024-July-15-2117.csv) and If have any further issues, please contact me.
2, i have done the null checking of all the component i finished

2024-07-16 05:08 UTC, RuntaoZhuge approved these changes

2024-07-16 05:08 UTC, merged